<a href="https://colab.research.google.com/github/sonudk/Introduction_to_AI_and_IoT-/blob/master/iris_mln.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification of iris dataset using MLN
## Prof. Laxmidhar Behera
### IIT Kanpur

### Loading libraries and data

In [0]:
from sklearn.datasets import load_iris
import numpy as np

np.random.seed(10) # For random weight initialization

iris = load_iris() # iris is a python dictionary with key-value pairs

#### Pre-process Data
Convert labels to categorical - One-hot encoding

In [0]:
X = iris['data']
Y = iris['target']
from keras.utils import to_categorical

Ny = len(np.unique(Y)) # Ny is number of categories/classes


Y = to_categorical(Y[:], num_classes = Ny) # 

Using TensorFlow backend.


#### Train - Test split
#### Data Normalization/Scaling

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 1)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train) # Computes the mean and standard deviation

X_train = scaler.transform(X_train) # Perform transformation: x = (x-mean)/std
X_test = scaler.transform(X_test)

### Keras

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
model = Sequential()
model.add(Dense(10, input_dim=X_train.shape[1], activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(Ny, activation='softmax')) # 'sigmoid'
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) # 'binary_crossentropy'
    # 'adam', 'adagrad', 'sgd'

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_10 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_11 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_12 (Dense)             (None, 3)                 33        
Total params: 303
Trainable params: 303
Non-trainable params: 0
_________________________________________________________________


In [0]:
# Fit the model
model.fit(X_train, Y_train, epochs=500, batch_size=100)

Epoch 1/500
120/120 [==============================] - 1s 9ms/step - loss: 1.1511 - acc: 0.3083
Epoch 2/500
120/120 [==============================] - 0s 42us/step - loss: 1.1457 - acc: 0.3083
Epoch 3/500
120/120 [==============================] - 0s 41us/step - loss: 1.1406 - acc: 0.3083
Epoch 4/500
120/120 [==============================] - 0s 42us/step - loss: 1.1359 - acc: 0.3083
Epoch 5/500
120/120 [==============================] - 0s 34us/step - loss: 1.1317 - acc: 0.3083
Epoch 6/500
120/120 [==============================] - 0s 36us/step - loss: 1.1274 - acc: 0.3083
Epoch 7/500
120/120 [==============================] - 0s 42us/step - loss: 1.1243 - acc: 0.3083
Epoch 8/500
120/120 [==============================] - 0s 42us/step - loss: 1.1209 - acc: 0.3083
Epoch 9/500
120/120 [==============================] - 0s 76us/step - loss: 1.1176 - acc: 0.3083
Epoch 10/500
120/120 [==============================] - 0s 58us/step - loss: 1.1147 - acc: 0.3083
Epoch 11/500
120/120 [========

120/120 [==============================] - 0s 33us/step - loss: 1.0372 - acc: 0.6417
Epoch 85/500
120/120 [==============================] - 0s 33us/step - loss: 1.0358 - acc: 0.6583
Epoch 86/500
120/120 [==============================] - 0s 33us/step - loss: 1.0344 - acc: 0.6917
Epoch 87/500
120/120 [==============================] - 0s 33us/step - loss: 1.0330 - acc: 0.6917
Epoch 88/500
120/120 [==============================] - 0s 24us/step - loss: 1.0315 - acc: 0.6917
Epoch 89/500
120/120 [==============================] - 0s 25us/step - loss: 1.0300 - acc: 0.6917
Epoch 90/500
120/120 [==============================] - 0s 25us/step - loss: 1.0285 - acc: 0.6917
Epoch 91/500
120/120 [==============================] - 0s 25us/step - loss: 1.0269 - acc: 0.6917
Epoch 92/500
120/120 [==============================] - 0s 25us/step - loss: 1.0254 - acc: 0.6917
Epoch 93/500
120/120 [==============================] - 0s 34us/step - loss: 1.0239 - acc: 0.6917
Epoch 94/500
120/120 [===========

120/120 [==============================] - 0s 33us/step - loss: 0.7935 - acc: 0.7000
Epoch 168/500
120/120 [==============================] - 0s 33us/step - loss: 0.7894 - acc: 0.7000
Epoch 169/500
120/120 [==============================] - 0s 58us/step - loss: 0.7853 - acc: 0.7000
Epoch 170/500
120/120 [==============================] - 0s 42us/step - loss: 0.7812 - acc: 0.7000
Epoch 171/500
120/120 [==============================] - 0s 48us/step - loss: 0.7771 - acc: 0.7000
Epoch 172/500
120/120 [==============================] - 0s 50us/step - loss: 0.7730 - acc: 0.7000
Epoch 173/500
120/120 [==============================] - 0s 58us/step - loss: 0.7689 - acc: 0.7000
Epoch 174/500
120/120 [==============================] - 0s 58us/step - loss: 0.7647 - acc: 0.6917
Epoch 175/500
120/120 [==============================] - 0s 42us/step - loss: 0.7610 - acc: 0.6917
Epoch 176/500
120/120 [==============================] - 0s 50us/step - loss: 0.7569 - acc: 0.6917
Epoch 177/500
120/120 [=

120/120 [==============================] - 0s 33us/step - loss: 0.5611 - acc: 0.7417
Epoch 250/500
120/120 [==============================] - 0s 47us/step - loss: 0.5595 - acc: 0.7417
Epoch 251/500
120/120 [==============================] - 0s 33us/step - loss: 0.5579 - acc: 0.7417
Epoch 252/500
120/120 [==============================] - 0s 42us/step - loss: 0.5564 - acc: 0.7417
Epoch 253/500
120/120 [==============================] - 0s 42us/step - loss: 0.5549 - acc: 0.7417
Epoch 254/500
120/120 [==============================] - 0s 57us/step - loss: 0.5534 - acc: 0.7333
Epoch 255/500
120/120 [==============================] - 0s 25us/step - loss: 0.5520 - acc: 0.7333
Epoch 256/500
120/120 [==============================] - 0s 31us/step - loss: 0.5508 - acc: 0.7333
Epoch 257/500
120/120 [==============================] - 0s 35us/step - loss: 0.5494 - acc: 0.7333
Epoch 258/500
120/120 [==============================] - 0s 58us/step - loss: 0.5481 - acc: 0.7167
Epoch 259/500
120/120 [=

120/120 [==============================] - 0s 33us/step - loss: 0.4668 - acc: 0.8833
Epoch 332/500
120/120 [==============================] - 0s 35us/step - loss: 0.4656 - acc: 0.8917
Epoch 333/500
120/120 [==============================] - 0s 32us/step - loss: 0.4644 - acc: 0.8833
Epoch 334/500
120/120 [==============================] - 0s 50us/step - loss: 0.4632 - acc: 0.8833
Epoch 335/500
120/120 [==============================] - 0s 33us/step - loss: 0.4620 - acc: 0.8833
Epoch 336/500
120/120 [==============================] - 0s 33us/step - loss: 0.4610 - acc: 0.8833
Epoch 337/500
120/120 [==============================] - 0s 36us/step - loss: 0.4599 - acc: 0.8833
Epoch 338/500
120/120 [==============================] - 0s 33us/step - loss: 0.4589 - acc: 0.8833
Epoch 339/500
120/120 [==============================] - 0s 33us/step - loss: 0.4577 - acc: 0.8833
Epoch 340/500
120/120 [==============================] - 0s 33us/step - loss: 0.4566 - acc: 0.8833
Epoch 341/500
120/120 [=

120/120 [==============================] - 0s 54us/step - loss: 0.3752 - acc: 0.8917
Epoch 414/500
120/120 [==============================] - 0s 33us/step - loss: 0.3738 - acc: 0.8917
Epoch 415/500
120/120 [==============================] - 0s 36us/step - loss: 0.3725 - acc: 0.8917
Epoch 416/500
120/120 [==============================] - 0s 25us/step - loss: 0.3711 - acc: 0.8917
Epoch 417/500
120/120 [==============================] - 0s 33us/step - loss: 0.3696 - acc: 0.8917
Epoch 418/500
120/120 [==============================] - 0s 32us/step - loss: 0.3681 - acc: 0.8917
Epoch 419/500
120/120 [==============================] - 0s 33us/step - loss: 0.3665 - acc: 0.8917
Epoch 420/500
120/120 [==============================] - 0s 25us/step - loss: 0.3653 - acc: 0.9000
Epoch 421/500
120/120 [==============================] - 0s 25us/step - loss: 0.3637 - acc: 0.9167
Epoch 422/500
120/120 [==============================] - 0s 25us/step - loss: 0.3623 - acc: 0.9167
Epoch 423/500
120/120 [=

120/120 [==============================] - 0s 42us/step - loss: 0.2708 - acc: 0.9667
Epoch 496/500
120/120 [==============================] - 0s 42us/step - loss: 0.2696 - acc: 0.9667
Epoch 497/500
120/120 [==============================] - 0s 31us/step - loss: 0.2684 - acc: 0.9667
Epoch 498/500
120/120 [==============================] - 0s 58us/step - loss: 0.2673 - acc: 0.9667
Epoch 499/500
120/120 [==============================] - 0s 42us/step - loss: 0.2661 - acc: 0.9667
Epoch 500/500
120/120 [==============================] - 0s 33us/step - loss: 0.2650 - acc: 0.9667


In [0]:
# calculate predictions
predictions = model.predict(X_train)
# round predictions
rounded = [round(x[0]) for x in predictions]
print(rounded)

[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]


In [0]:
# evaluate the model
scores = model.evaluate(X_test, Y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

30/30 [==============================] - 0s 4ms/step

acc: 96.67%


In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
predictions = np.argmax(model.predict(X_test), axis=1)
Y_test = np.argmax(Y_test,axis=1)
print(confusion_matrix(Y_test,predictions))  
print(classification_report(Y_test,predictions))  

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

   micro avg       0.97      0.97      0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

