<a href="https://colab.research.google.com/github/sonudk/Introduction_to_AI_and_IoT-/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

### Numpy arrays

In [0]:
l = [1, 2, 3, 4, 5]
print(type(l))
l_a = np.array(l)
print(l_a, 'Type of l_a is ', type(l_a))

<class 'list'>
[1 2 3 4 5] Type of l_a is  <class 'numpy.ndarray'>


In [0]:
l_a = l_a + 10
print(l_a)

[11 12 13 14 15]


In [0]:
l = [[1, 2, 3], [4, 5, 6]]
l_a = np.array(l)
print(l_a)

[[1 2 3]
 [4 5 6]]


In [0]:
## 2x2x2

In [0]:
l_a.shape

(2, 3)

In [0]:
l = [[[1, 2, 3], [5, 6, 7], [9, 10, 11]], [[1, 2, 3], [5, 6, 7], [9, 10, 11]]]

In [0]:
l_a = np.array(l)

In [0]:
l_a.shape  #(2, 3, 3) # (2, ) #

(2, 3, 3)

In [0]:
print(l_a)

[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]

 [[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]]


In [0]:
l_a.shape

(2, 3, 3)

In [0]:
l_a.size

18

In [0]:
l_a.ndim

3

In [0]:
l_a.max()

11

In [0]:
l_a.min()

1

In [0]:
np.mean(l_a)

6.0

In [0]:
l_a.shape

(2, 3, 3)

In [0]:
l_a

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]]])

In [0]:
l = [[1, 2, 3], [1, 2, 3]]

In [0]:
np.array(l).astype('float').dtype

dtype('float64')