<a href="https://colab.research.google.com/github/sonudk/Introduction_to_AI_and_IoT-/blob/master/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## Array Creation

In [6]:
l=[1,3,24,233223,2332323]
print(np.array(l),type(np.array(l)))
print(type(l))

[      1       3      24  233223 2332323] <class 'numpy.ndarray'>
<class 'list'>


In [8]:
# Create an array from list
l = [1, 2, 3 ,4 , 5]
l_a = np.array(l)
print(l_a, type(l_a))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
l=[[1,233,23,32300],[2,3,23,23]]
print(np.array(l))

[[    1   233    23 32300]
 [    2     3    23    23]]


In [10]:
l2 = [[1, 2, 3], [4, 5, 6]]
l2_a = np.array(l2)
print(l2_a, type(l2_a))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [0]:
## initialize an array with zeros
l3_a = np.zeros((3, 3))
print(l3_a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
## initialize with ones
l4_a = np.ones((3, 3))
print(l4_a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.array(()))

[]


In [16]:
print(np.empty((2,3),dtype=np.float64))

[[3.43025904e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [18]:
### empty array
## see both the empty matrices are samein float64 data type# it doesn't depend on how much time we run cells
l5_a = np.empty((2, 3))
print(l5_a)

[[3.43025904e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [22]:
l_0_to10 = list(range(21)) # last pointdoes not considerd
print(l_0_to10)
print(np.random.shuffle(np.array(l_0_to10))) #why it shows none

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
None


In [23]:
l7_a = np.arange(10, 20, 2) # start, end, step size# can be used to generate evenly sepoerated random datas #######$$$$$$$$$$$last point 20 doesn't come ##################
print(l7_a)

[10 12 14 16 18]


### Basic Operations

In [0]:
l6_a = l4_a + 2
print(l6_a)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [0]:
## ** is used for exponentiation
print(2**2)
print(l6_a**2)

4
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [0]:
np.sin(l6_a)

array([[0.14112001, 0.14112001, 0.14112001],
       [0.14112001, 0.14112001, 0.14112001],
       [0.14112001, 0.14112001, 0.14112001]])

In [0]:
l8_a = np.arange(1, 10).reshape(3, 3)
print(l8_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
print(l8_a > 5)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [0]:
l2s = np.ones((3, 3))*2
print(l2s)
l3s = np.ones((3, 3))*3
print(l3s)
print(l2s*l3s) ## @@@$$$element wise multiplication of both arrays


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [0]:
print(l2s.dot(l3s)) ## dot product

[[18. 18. 18.]
 [18. 18. 18.]
 [18. 18. 18.]]


In [0]:
print(l2s@l3s) # another way to do dot product of matrices### #this is awesome

[[18. 18. 18.]
 [18. 18. 18.]
 [18. 18. 18.]]


In [0]:
for i in range(5):
    

In [0]:
### create 3x3 matrices with all 1s, all 2s, so on , all 5s. Square them and add them

## simple list of ints
list_ints = []
for i in range(1, 6):
    list_ints.append(i)

l_matrices = []
for i in range(1, 6):
    three_by_three = np.ones((3, 3))*i
    l_matrices.append(three_by_three)
print(l_matrices)

sum_squares = np.zeros((3, 3))
for i in l_matrices:
    sum_squares = sum_squares + i*i

print(sum_squares)

[array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]]), array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]]), array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]]), array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]]), array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])]
[[55. 55. 55.]
 [55. 55. 55.]
 [55. 55. 55.]]


In [0]:
l1s = np.ones((3, 3))
l1s.sum()

9.0

In [0]:
l_1 = np.arange(1, 13).reshape(4, 3)
print(l_1)
l_1.max()

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


12

### Axis

In [6]:
import numpy as np
l_6 = np.array([[ 1 , 2 , 3],
                [ 4 , 5 , 6],
                [ 7 , 89,  9],
                [10 , 11, 12]])
l_6.max(axis = 0)

array([10, 89, 12])

In [7]:
l_6.max(axis = 1)

array([ 3,  6, 89, 12])

In [8]:
l_6.sum(axis = 0)

array([ 22, 107,  30])

In [0]:
l_1.sum(axis = 1)

array([ 6, 15, 24, 33])

In [0]:
l_2 = np.arange(24).reshape(2, 3, 4)
print(l_2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [0]:
l_2.max(axis = 1).shape # don't show the shape wrt which axis we are taking shape

(2, 4)

In [0]:
l_2.max(axis = 1)

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [0]:
l_2.max(axis = 2)

array([[ 3,  7, 11],
       [15, 19, 23]])

In [0]:
l_3 = np.arange(16).reshape(4, 2, 2)
print(l_3)
print('\n')
for i in l_3:
    print(i)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 8  9]
 [10 11]]
[[12 13]
 [14 15]]


In [0]:
for i in l_3.flat:
    print(i)

0
1
2
3
4
5
6
7
8


In [0]:
l_10 = np.arange(24)
print(l_10.reshape(2, 3, 4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Stacking

In [0]:
l1 = np.arange(3)
l2 = np.arange(3, 6)
print(l1, l2)

[0 1 2] [3 4 5]


In [0]:
np.vstack([l1, l2])

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
y = np.array([0, 1, 0, 1, 1, 1, 1, 0, 0, 1])
print(y.shape)
x = np.arange(20).reshape(10, 2)
print('x', x)
print('y', y)

(10,)
x [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
y [0 1 0 1 1 1 1 0 0 1]


In [0]:
x_0 = []
x_1 = []
index = 0
for i in x:
    if(y[index] == 0):
        x_0.append(i)
    else:
        x_1.append(i)
    index = index + 1

print('before stacking', x_0)
v_x_0 = np.vstack(x_0)
v_x_1 = np.vstack(x_1)
    
print(v_x_0,'\n\n\n', v_x_1)    

before stacking [array([0, 1]), array([4, 5]), array([14, 15]), array([16, 17])]
[[ 0  1]
 [ 4  5]
 [14 15]
 [16 17]] 


 [[ 2  3]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [18 19]]


In [0]:
h_x_0 = np.hstack([i.reshape(2, 1) for i in x_0])
print(h_x_0)

[[ 0  4 14 16]
 [ 1  5 15 17]]


In [0]:
t1 = np.arange(6).reshape(2, 3)
print(t1)
t2 = np.arange(10, 12).reshape(2, 1)
print(t2)
np.hstack([t1, t2])

[[0 1 2]
 [3 4 5]]
[[10]
 [11]]


array([[ 0,  1,  2, 10],
       [ 3,  4,  5, 11]])

In [0]:
np.concatenate([t1, t2], axis = 1)

array([[ 0,  1,  2, 10],
       [ 3,  4,  5, 11]])