<a href="https://colab.research.google.com/github/sonudk/Introduction_to_AI_and_IoT-/blob/master/solved_in_class_Assignment_data_rep_evalution_f.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Generate Random array
Generate a numpy array of shape x with random values as its elements.





In [0]:
import numpy as np

In [0]:
def generate_array(x):
  '''
  input:
    x: tuple defining shape; Eg., (5, 2, 3)
  output:
    y: numpy array of shape x generated using numpy.random library
        and its elements as random values between [0,1).
  '''
  # YOUR CODE HERE
  y = np.random.random(x)
  return y


In [3]:
'''test for generate_array'''
def test_generate_array():
  x = (2,4,5,6)
  y = generate_array(x)
  assert y.shape==x
  assert np.all(y<1)
  assert np.all(y>=0)
  print('Test passed', '\U0001F44D')
test_generate_array()

Test passed 👍


### Shape
Write a python function to calculate shape of a given array.

In [0]:
def return_shape(x):
  '''
  input:
    x: a numpy array of any dimension
  output:
    y: shape of input array as a tuple.
  '''
  # YOUR CODE HERE


In [0]:
'''test for return_shape'''
def test_return_shape():
  x = np.array([1,2])
  y = return_shape(x)
  assert y == (2,)
  print('Test passed', '\U0001F44D')
test_return_shape()

### Mean and STD
Given a data tensor X,  with axis=0 indexing the samples, find mean and standard deviation of the samples .

In [0]:
def CalculateMeanStddev(x):
  '''
  input:
    x: a numpy array of any dimension
  output:
    mean: Numpy array with mean of input samples
    stddev: Numpy array with standard deviation of input samples
  
  HINT: Shape of Input is (samples, feature1, feature2, ...)
  
  Return mean,stddev
  '''
  # YOUR CODE HERE
  # Mean
  sumx = x[0] * 0
  for i in range(x.shape[0]):
    sumx = sumx + x[i]
  meanx = sumx/x.shape[0]
  # Std Dev.
  sumofsq = x[0] * 0
  for i in range(x.shape[0]):
    sumofsq = sumofsq + (x[i]-meanx)*(x[i]-meanx)
  varx = sumofsq/x.shape[0]
  stddevx = np.sqrt(varx)
  return meanx, stddevx


[[[3.38756923e-01 4.47208036e-05 6.03771163e-01 6.74502877e-01
   5.10913289e-02 8.61653461e-01]
  [4.08893788e-01 3.32264755e-01 3.32942331e-01 2.47981839e-02
   3.57149570e-01 4.39373031e-01]
  [4.47439637e-03 5.65657723e-01 5.40019119e-01 9.48573263e-02
   4.15213716e-01 3.97103782e-01]
  [8.59634200e-01 7.49648219e-01 4.64338955e-02 1.85440857e-01
   9.02509827e-01 7.31019958e-01]
  [3.99881935e-01 3.28224061e-01 1.68257512e-02 1.15213306e-01
   3.70085254e-01 3.40511667e-01]
  [6.40982119e-01 8.31637091e-01 2.75244615e-01 2.52526468e-01
   8.23145637e-01 4.76634558e-01]]

 [[6.09306241e-01 8.86290301e-01 2.21656965e-01 3.17331971e-01
   7.43907587e-01 1.23887898e-01]
  [4.56774445e-01 6.99737485e-01 8.06973887e-01 9.14110370e-01
   3.52778914e-01 9.60272565e-01]
  [3.85495470e-02 7.45964801e-01 4.33193139e-01 5.77570500e-01
   4.17981578e-01 2.54405148e-02]
  [7.89546880e-01 4.11825561e-01 3.77705400e-02 1.46862276e-01
   3.57560280e-01 4.93570847e-01]
  [4.18626305e-01 9.83577880

In [0]:
'''test for CalculateMeanStddev'''
def test_CalculateMeanStddev():
  X = np.array([[1,2,3],
                [5,3,1],
                [3,7,9],
                [3,5,6]])
  mean, stddev = CalculateMeanStddev(X)
  assert np.all(np.isclose(mean, np.array([3.  , 4.25, 4.75])))
  assert np.all(np.isclose(stddev, np.array([1.41421356, 1.92028644, 3.03108891]) ))

  print('Test passed', '\U0001F44D')
test_CalculateMeanStddev()

Test passed 👍


In [0]:
a = 2
a[0]

TypeError: 'int' object is not subscriptable

### Index
Given a matrix of size (m,n) find the element at index position i = a, j =b (start indexing from 0)
(Note: If m<a+1 or n<b+1, then return 'None') 


In [0]:
def element_at_given_index_position(x,a,b):
  '''
  input:
    x: numpy array of shape (m,n)
    a: integer value (row)
    b: integer value (column)
  output:
    y: element at index position (a,b)
  '''
  # YOUR CODE HERE
  print(x.shape)
  if a<x.shape[0] and b<x.shape[1]:
      y = x[a,b]
  else:
    y = None
  return y
x = np.random.random((2,3))
a = 5
b = 1
y = element_at_given_index_position(x,a,b)
print(y)

(2, 3)
None


In [0]:
'''test for  element_at_given_index_position'''
def test_element_at_given_index_position():
  
  
  x = np.array([[1,2,3],
                [5,3,1],
                [3,7,9],
                [3,5,6],
                [1,2,3],
                [5,7,8]])
  z =  element_at_given_index_position(x,5,2)
  assert z ==8
  print('Test passed', '\U0001F44D')
  
test_element_at_given_index_position()

### Batch splitting
Given a data matrix X with axis = 0 for samples, split X into batches of 'm' samples each.
Note: last batch can have  less than 'm' samples.
Output should be list of numpy arrays.

In [0]:
def split_data(x,m):
  '''
  input:
    x: 2d numpy array of any shape (with axis = 0 indicating samples)
    m: integer (sample size iin each batch)
  output:
    y: a list containing numpy arrays with 'm' samples in each array and 
    can be less than m only in last array
  '''
  # YOUR CODE HERE
  Xbatches = []
  Nb = int(np.ceil(x.shape[0]/m))
  print(Nb)
  for b in range(Nb):
    batch = x[b*m:(b+1)*m, :]
    Xbatches.append(batch)
  return Xbatches

x = np.random.random((7,3))
print(x)
split_data(x,3)

[[0.25516657 0.95262906 0.71446436]
 [0.90205046 0.24208297 0.68566086]
 [0.96508546 0.651543   0.21183336]
 [0.41428521 0.32099976 0.1412156 ]
 [0.59804251 0.86676516 0.99140249]
 [0.56331274 0.1023093  0.57699483]
 [0.01203685 0.04330308 0.16109874]]
3


[array([[0.25516657, 0.95262906, 0.71446436],
        [0.90205046, 0.24208297, 0.68566086],
        [0.96508546, 0.651543  , 0.21183336]]),
 array([[0.41428521, 0.32099976, 0.1412156 ],
        [0.59804251, 0.86676516, 0.99140249],
        [0.56331274, 0.1023093 , 0.57699483]]),
 array([[0.01203685, 0.04330308, 0.16109874]])]

In [0]:
'''test for  element_at_given_index_position'''
def test_split_data():
  
  
  x = np.array([[1,2,3],
                [5,3,1],
                [3,7,9],
                [3,5,6],
                [11,12,13],
                [5,7,8],
                [1,2,3],
                [5,3,1],
                [3,7,9],
                [3,5,6],
                [11,12,13],
                [5,7,8]])
  z = split_data(x,5)
  assert np.all(z[0]==np.array([[ 1,  2,  3],
       [ 5,  3,  1],
       [ 3,  7,  9],
       [ 3,  5,  6],
       [11, 12, 13]]))
  
  assert np.all(z[1]==np.array([[5, 7, 8],
       [1, 2, 3],
       [5, 3, 1],
       [3, 7, 9],
       [3, 5, 6]]))
  
  assert np.all(z[2]==np.array([[11, 12, 13],
       [ 5,  7,  8]]))

  print('Test passed', '\U0001F44D')
  
test_split_data()

3
Test passed 👍


### Shuffle
Given a data tensor X with axis = 0 indexing the sample, randomly shuffle the samples.

In [0]:
def shuffle_samples(x):
  '''
  input:
    x: any general numpy array of dimension (m,n)
  output:
    y: a numpy array with dimension same as of input array but 
    samples are shuffled randomly.
  '''
  # YOUR CODE HERE
  np.random.shuffle(x)
  return x

x = np.random.random((4,3))
print(x)
print(shuffle_samples(x))

[[0.098908   0.14188205 0.14854951]
 [0.24550464 0.28257086 0.18545657]
 [0.66711692 0.52437794 0.43362828]
 [0.74019446 0.47634705 0.71707142]]
[[0.66711692 0.52437794 0.43362828]
 [0.24550464 0.28257086 0.18545657]
 [0.74019446 0.47634705 0.71707142]
 [0.098908   0.14188205 0.14854951]]


In [0]:
def test_shuffle_samples():
  x = np.array([[1,2,3],
                [5,3,1],[6,8,0]])
  shuffle_samples(x)
  assert x.shape == (3,3)
  print('Test passed', '\U0001F44D')
  
test_shuffle_samples()

### 1-hot encoding
Given three classes, encode them as one hot encoded vectors. For example, if
y = [0, 1, 2] then one hot encoded y = [ [1, 0, 0] , [0, 1, 0] , [0, 0, 1] ]

In [0]:
def oneHot(y, Ny):
  import numpy as np
  
  '''
  Input:
      y: an int in {0, 1, 2}
      Ny: Number of classes, e.g., 3 here.
  Output:
      Y: a vector of Ny (=3) tuples
    '''
  # YOUR CODE HERE
  Y = np.zeros(Ny)
  Y[y]=1
  return Y

oneHot(1,3)

array([0., 1., 0.])

In [0]:
def test_oneHot():
    assert np.all(oneHot(0,3)==np.array([1,0,0]))
    assert np.all(oneHot(1,3)==np.array([0,1,0]))
    assert np.all(oneHot(2,3)==np.array([0,0,1]))
    assert Y_train.shape[1]==3
    print("Test passed', '\U0001F44D")
test_oneHot()

Given desired output in a list, convert output into one hot encoded vectors.

In [0]:
def one_hot_encoding_output(x):
  '''
  input:
    x: a list containing desired output, for exmple x = ['cat', 'dog', 'mouse', 'cat', 'cat', 'mouse']
  output:
    y: numpy array with one hot encoded vectors as its elements.
  '''
  # YOUR CODE HERE
  print(x)
  # Make a list of unique elements in x, call it categories
  categories = []
  for item in x:
    if item not in categories:
        categories.append(item)
    else:
        pass
  print (categories)
  # For each element in x, x_ind contains the index of that element
  x_ind = []
  for element in x:
    index = categories.index(element)
    x_ind.append(index)
  # For each element in x_ind, find the 1-hot encoded form
  x_1hot = []
  for index in x_ind:
    onehotvec = oneHot(index, len(categories))
    x_1hot.append(onehotvec)
  y = np.array(x_1hot)
  return y
  

x = ['cat', 'dog', 'mouse', 'cat', 'cat', 'mouse', 'human', 'human']
one_hot_encoding_output(x)

['cat', 'dog', 'mouse', 'cat', 'cat', 'mouse', 'human', 'human']
['cat', 'dog', 'mouse', 'human']


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [0]:
def test_one_hot_encoding_output():
    x = ['cat', 'dog', 'mouse']
    one_hot_encoding_output(x)[0]
    assert np.all(one_hot_encoding_output(x)[2]==np.array([0., 0., 1.]))
    assert np.all(one_hot_encoding_output(x)[1]==np.array([0., 1., 0.]))
    assert np.all(one_hot_encoding_output(x)[0]==np.array([1., 0., 0.]))
    print("Test passed', '\U0001F44D")
test_one_hot_encoding_output()

['cat', 'dog', 'mouse']
['mouse', 'cat', 'dog']
['cat', 'dog', 'mouse']
['mouse', 'cat', 'dog']


AssertionError: 

Given a data tensor X, with axis = 0 indexing the samples, randomly pick 10 samples and return as a numpy tensor.
If there are less than 10 samples, pad the output tensor with samples having all values as zero(hint. - padded samples will have same dimension as of input samples)


In [0]:
def pick_samples(x):
  '''
  input:
    x: a numpy array of shape (m,n) (Note: it may have less than 10 samples also. Your code should be fit for 
    both conditions i.e. m<10 or m>10 )
  output:
    y: numpy array containing 10 samples selected by randomly shuffling input array and padding samples with all 
    elements as zeros if input array has less than 10 samples.
    .
  '''
  # YOUR CODE HERE

In [0]:
def test_pick_sample():
    x = np.array([[1,2,3],
                 [5,3,1],
                 [3,7,9]])
    z = pick_samples(x)
    assert z.shape==(10,x.shape[1])
    print("Test passed', '\U0001F44D")
test_pick_sample()

In [0]:
def test_pick_sample():
   
  x = np.array([[1,2,3],
                [5,3,1]])
  Z = np.array
  assert np.all(one_hot_encoding_output(x)[2]==np.array([0., 0., 1.]))
  assert np.all(one_hot_encoding_output(x)[1]==np.array([0., 1., 0.]))
  assert np.all(one_hot_encoding_output(x)[0]==np.array([1., 0., 0.]))
  print("Test passed', '\U0001F44D")
test_one_hot_encoding_output()
  

### Confusion Matrix
Given the true output values of a classification task is a numpy vector Ytrue
and the estimated output values is  a numpy vector Yest , your function should return
the confusion matrix. Do not use any standard library.

In [0]:
def draw_confusion_matrix(yest,ytrue):
  '''
  input:
    yest: one dimensional numy array consisting of predicted output values(for example  yest = [ 1, 0, 0, 1, 0, 0, 1, 1, 1, 0 ] )
    ytrue: one dimensional numy array consisting of actual output values)( for example, ytrue = [ 1, 1, 0, 1, 0, 0, 1, 0, 0, 0 ] )
  output:
    y: confusion matrix as a numpy array 
    .
  '''
  # YOUR CODE HERE

In [0]:
''' check for draw confusion matrix'''

from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve
import numpy as np


expected = [ 1, 0, 0, 1, 0, 0, 1, 1, 1, 0 ]
predicted = [ 1, 1, 0, 1, 0, 0, 1, 0, 0, 0 ]
results = confusion_matrix(expected, predicted)
assert np.all(draw_confusion_matrix(expected,predicted) == results)
print("Test passed', '\U0001F44D")


Given the confusion matrix CM = np.array([[40 20 10],
                                                                          [10 30 5],
                                                                          [2 1 50]])
 

1.   What is the accuracy? Save it as 'acc.'.
2.   What is precision? Save it as 'prec' in a numpy array.
3.   What is recall? Save it as 'recall' in a numpy array
4.   What is F-1 score? Save it as 'F_1' in a numpy array





In [0]:
def confusion_matrix_metrics(CM):
  '''
    input:
      CM: confusion matrix
    output:
      accuracy: Accuracy across all classes
      precision: Numpy array with precision for each class
      recall: Numpy array with recall for each class
      F_1 : Numpy array with f_1 score for each class
      
      Return the results as a tuple (accuracy, precision, recall, f_1)
  '''
  # YOUR CODE HERE

In [0]:
''' check for confusion matrix'''

def test_confusion_matrix_metrics():
  CM = np.array([[40,20,10], [10,30,5], [2,1,50]])
  accuracy, precision, recall, F_1 = confusion_matrix_metrics(CM) 
  
  assert np.isclose(accuracy, 0.7142857142857143)
  assert np.all(np.isclose(precision, np.array([0.7692307692307693, 0.5882352941176471, 0.7692307692307693])))
  assert np.all(np.isclose(recall, np.array([0.5714285714285714, 0.6666666666666666, 0.9433962264150944])))
  assert np.all(np.isclose(F_1, np.array([0.6557377049180327, 0.625, 0.847457627118644])))
  print("Test passed', '\U0001F44D")
  
test_confusion_matrix_metrics()

In [0]:
40/52

0.7692307692307693